export const KEYS = {
  LOGIN: "login",
  REGISTER: "register",
  FORGOT_PASSWORD: "forgot-password",
  VERIFY_OTP: "verify-otp",
  RESEND_OTP: "resend-otp",
  RESET_PASSWORD: "reset-password",
  CHANGE_PASSWORD: "change-password",
  NEWSLETTER: "newsletter",
  HERO_BANNER: "hero-banner",
  COURSE_CATEGORY: "course-category",
  TESTIMONIALS: "testimonials",
  FAQ: "faq",
  TRUSTED_PARTNER: "trusted-partner",
  COURSE: "course",
  COURSE_ONE: "course-one",
  COURSE_CURRICULUM: "course-curriculum",
  INSTRUCTOR: "instructor",
  LEGALITY: "ligality",
  CONTACT: "contact",
  BLOG: "blog",
  BLOG_ONE: "blog-one",
  SETTINGS: "settings",
  GALLARY: "gallary",
  USER: "user",

} as const;
